services:
  postgres:
    image: postgres:15-alpine
    container_name: eventing-wal-postgres
    environment:
      POSTGRES_DB: eventing_wal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eventing_wal"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
